/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

/**
 *
 * @author LENOVO
 */
import Tabel.DataMember;
import Tabel.TabelDataMember;
import java.io.File;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
public class member extends javax.swing.JFrame {
    private Connection koneksi;
    private Statement script;
    private TabelDataMember ModelDataMember;
    /**
     * Creates new form member
     */
    public member() {
        initComponents();
        KoneksiDB();
        ModelDataMember = new TabelDataMember();
        tb_member.setModel(ModelDataMember);
        tampil();
        klikTabel();
    }
    
    private void Update(){
    int app;
     if ((app=JOptionPane.showConfirmDialog(null,"Ubah Data Member"+"?","Perhatian",
              JOptionPane.YES_NO_OPTION))==0) {
                   
                try{
                  String sql= " UPDATE tb_member set "
                          + "nama_member = '"+ tfNama.getText() + "', "
                          + "keterangan = '"+ listKeterangan.getSelectedValue() + "' "
                          + "where id_member = '"+ tfId.getText() + "'";
                  
                  script.executeUpdate(sql);
                  tampil();
                  bersih();
                    JOptionPane.showMessageDialog(null,"Data Member Berhasil Di Ubah ");
                }
                catch(SQLException ex){
                    System.err.print(ex);
                                     
                }  
            } 
}
    
    private void bersih(){
    tfId.setText(null);
    tfNama.setText(null);
    tfId.requestFocus();
    }
    
     private void Hapus(){
    int app;
    if((app=JOptionPane.showConfirmDialog(null,"Hapus data penjualan"+"?","Perhatian",
            JOptionPane.YES_NO_OPTION))==0){
    try{
        String sql="Delete from tb_member where"+" id_member = '"+tfId.getText()+"'";
        script.executeUpdate(sql);
        tampil();
        JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
        bersih();
    }
    catch(SQLException ex){
    System.err.print(ex);
       }
    }
}
     
    private void tampil(){
    try{
        int baris = tb_member.getRowCount();
        for(int i=0; i<baris; i++){
            ModelDataMember.delete(0, baris);
        }
        String sql = " select * from tb_member";
        ResultSet rs = script.executeQuery(sql);
        while (rs.next( )){
            DataMember member = new DataMember();
            
            member.setId(rs.getString(1));
            member.setNama(rs.getString(2));
            member.setKeterangan(rs.getString(3));
               
               ModelDataMember.add(member);
        }
    }
    catch(SQLException ex){
        System.err.print(ex);
        }
    }
     private void KoneksiDB(){
    try{
        Class.forName("com.mysql.jdbc.Driver");
        koneksi=DriverManager.getConnection("jdbc:mysql://localhost/kasir","root","");
        script=koneksi.createStatement();
    }
    catch (SQLException ex) {
        System.err.print (ex);
    }
    catch (ClassNotFoundException ex){
        System.err.print(ex);
    }
    }
     
     private void klikTabel(){
    tb_member.getSelectionModel().addListSelectionListener(new ListSelectionListener()
    {
      @Override
     public void valueChanged(ListSelectionEvent e)
            
     {
         int baris = tb_member.getSelectedRow();
         if(baris != -1)
        {
                DataMember member = ModelDataMember.get(baris);
            tfId.setText(member.getId());
            tfNama.setText(member.getNama());
            listKeterangan.setSelectedValue(member.getKeterangan(), true);
            }
        }
   });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jbSimpan = new javax.swing.JButton();
        jbUbah = new javax.swing.JButton();
        jbHapus = new javax.swing.JButton();
        jbPrint = new javax.swing.JButton();
        jbTutup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_member = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listKeterangan = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Member");

        jLabel2.setText("Nama");

        jLabel3.setText("Keterangan");

        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        jbSimpan.setText("Simpan");
        jbSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimpanActionPerformed(evt);
            }
        });

        jbUbah.setText("Ubah");
        jbUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUbahActionPerformed(evt);
            }
        });

        jbHapus.setText("Hapus");
        jbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHapusActionPerformed(evt);
            }
        });

        jbPrint.setText("Print");
        jbPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrintActionPerformed(evt);
            }
        });

        jbTutup.setText("Tutup");
        jbTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTutupActionPerformed(evt);
            }
        });

        tb_member.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_member);

        listKeterangan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Reguler", "Premium", "Super Premium", "VIP", "VVIP" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listKeterangan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jbUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbTutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(112, 112, 112))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSimpan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbUbah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbHapus)
                        .addGap(18, 18, 18)
                        .addComponent(jbPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbTutup))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void jbSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimpanActionPerformed
        // TODO add your handling code here:
        if (tfId.getText().length()==0){
           JOptionPane.showMessageDialog(null," Kode tidak boleh kosong","konfirmasi",JOptionPane.INFORMATION_MESSAGE);
           tfId.requestFocus();
           return;
        }
        else{ 
          //validasi redudansi
               try{
                String a="select * from tb_member where "+"id_member='"+tfId.getText()+"'";
                ResultSet res = script.executeQuery(a);
                if (res.next()){
                    if (tfId.getText().equals(res.getString("id_member"))){
                        JOptionPane.showMessageDialog(rootPane," Kode sudah ada");
                        tfId.requestFocus();
                        return;
                    }
                }
            //coding simpan    
                try{
                  String sql= " insert into tb_member values ("
                    + "'"+tfId.getText()+"',"      
                    + "'"+tfNama.getText()+"',"
                    + "'"+ String.join(",", listKeterangan.getSelectedValuesList())+"'"
                    +")";
                  script.executeUpdate(sql);
                  
                  JOptionPane.showMessageDialog(null,tfId.getText()+" Berhasil disimpan");
                  bersih();
                  tampil();
                }
                catch(SQLException ex){
                    System.err.print(ex);
                }  
            } 
            catch (Exception e){
                JOptionPane.showMessageDialog(rootPane,"Ada yang Salah");
            } 
      }
    }//GEN-LAST:event_jbSimpanActionPerformed

    private void jbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHapusActionPerformed
        // TODO add your handling code here:
        Hapus();
    }//GEN-LAST:event_jbHapusActionPerformed

    private void jbTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTutupActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbTutupActionPerformed

    private void jbUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUbahActionPerformed
        // TODO add your handling code here:
        Update();
    }//GEN-LAST:event_jbUbahActionPerformed

    private void jbPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrintActionPerformed
        // TODO add your handling code here:
        try
        {
            File report2 = new File("src/Laporan/report2.jasper");
            KoneksiDB();
            JasperPrint jp = JasperFillManager.fillReport(report2.getPath(),null,koneksi);
            JasperViewer.viewReport(jp, false);
        }
        catch(JRException e)
                {
                    JOptionPane.showMessageDialog(rootPane,e);
                }
    }//GEN-LAST:event_jbPrintActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbHapus;
    private javax.swing.JButton jbPrint;
    private javax.swing.JButton jbSimpan;
    private javax.swing.JButton jbTutup;
    private javax.swing.JButton jbUbah;
    private javax.swing.JList<String> listKeterangan;
    private javax.swing.JTable tb_member;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    // End of variables declaration//GEN-END:variables
}
